# Generated by Django 3.2.9 on 2021-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_web', models.IntegerField()),
                ('link_from_web', models.CharField(max_length=200)),
                ('image_form_web', models.ImageField(upload_to='')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
