# Generated by Django 3.2.9 on 2021-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RandomFox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fox',
            name='image_form_web',
            field=models.ImageField(upload_to='media/foxes/'),
        ),
    ]
